import { Property, Agent, TeamMember, BlogPost, Testimonial } from "@/types";

export const mockAgent: Agent = {
  id: "1",
  name: "Lara Murphy",
  title: "Broker / Owner",
  phone: "(704) 929-3289",
  email: "lara@carolinahorsefarmrealty.com",
  photo: "/images/team/lara-murphy.jpg",
  bio: "With over 15 years of experience in equestrian real estate.",
  specialties: ["Horse Farms", "Equestrian Estates", "Land for Horses"],
  licenseNumber: "NC-123456",
};

export const teamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Lara Murphy",
    title: "Broker / Owner",
    phone: "(704) 929-3289",
    email: "lara@carolinahorsefarmrealty.com",
    photo: "/images/team/lara-murphy.jpg",
    bio: "With over 15 years of experience in equestrian real estate.",
    specialties: ["Horse Farms", "Equestrian Estates", "Land for Horses"],
  },
];


export const mockProperties: Property[] = [
  {
    id: "1",
    mlsNumber: "4284811",
    title: "Working Equestrian Farm in Valley Farm Community",
    address: "4107 Cahnnas Way",
    city: "Waxhaw",
    state: "NC",
    zipCode: "28173",
    price: 925000,
    acreage: 10,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2447,
    yearBuilt: 2000,
    description: "Turnkey equestrian farm on 10 acres in the desirable Valley Farm community. This working horse property features a well-maintained 9-stall barn with tack room, hot and cold water, and a dedicated feed room. A 100x150 lighted riding arena with quality footing makes year-round training possible. Four fenced pastures with run-in shelters provide ample turnout. The 3-bedroom ranch home offers comfortable living with an open floor plan and views of the pastures. Conveniently located near Mineral Springs Greenway and the 1,100-acre Cane Creek Park with miles of riding trails.",
    images: ["/images/properties/property-1-hero.jpg", "/images/properties/property-1-barn.jpg", "/images/properties/property-1-pasture.jpg"],
    features: ["Open Floor Plan", "Lighted Arena", "Sprinkler System on Arena", "4-Bay Equipment Shed", "Run-in Shed", "Trail Access Nearby"],
    equestrianAmenities: {
      stalls: 9,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 4,
      pastureAcreage: 7,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Wire"],
      waterSource: ["Well"],
      barnSquareFeet: 3600,
      additionalStructures: ["Equipment Shed", "Run-in Shed"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-09-15",
    propertyType: "farm",
  },
  {
    id: "2",
    mlsNumber: "3330191",
    title: "Equestrian-Ready Barn Property on McWhorter Road",
    address: "6505 McWhorter Road",
    city: "Waxhaw",
    state: "NC",
    zipCode: "28173",
    price: 289900,
    acreage: 7,
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 0,
    yearBuilt: 0,
    description: "Outstanding opportunity to build your dream equestrian property on 7 beautiful acres in Union County. The property comes with an existing barn featuring 8 matted 12x12 stalls equipped with water, electricity, and fans. Fenced pastures are ready for horses. The gently rolling terrain with mature trees offers an ideal setting for a custom home and additional equestrian facilities. Located in a quiet, rural area of Waxhaw with easy access to local amenities and Charlotte.",
    images: ["/images/properties/property-2-hero.jpg", "/images/properties/property-2-barn.jpg", "/images/properties/property-2-land.jpg"],
    features: ["Existing Barn with 8 Stalls", "Matted Stalls", "Electric & Water to Barn", "Fans in Each Stall", "Fenced Pastures", "Mature Trees"],
    equestrianAmenities: {
      stalls: 8,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 2,
      pastureAcreage: 5,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board", "Wire"],
      waterSource: ["Well"],
      barnSquareFeet: 2400,
      additionalStructures: [],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-06-20",
    propertyType: "land",
  },
  {
    id: "3",
    mlsNumber: "73553",
    title: "Covered Arena on Major Trail System",
    address: "250 Burt Blackwell Road",
    city: "Mill Spring",
    state: "NC",
    zipCode: "28756",
    price: 1549000,
    acreage: 25,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2679,
    yearBuilt: 2005,
    description: "Custom mountain retreat on 25 acres with exceptional equestrian facilities just minutes from the Tryon International Equestrian Center. The home features hand-hewn beams, a cozy wood stove, and a main-level primary suite designed for outdoor living. Two fenced pastures totaling approximately 6 acres provide excellent turnout. A 2-stall stable with tack room serves daily needs, while the impressive 190x85 riding arena with quality all-weather footing allows year-round training. A loop trail suitable for horseback riding winds through the wooded portions of the property. A 60x40 workshop with apartment above offers additional living space or farm staff quarters.",
    images: ["/images/properties/property-3-hero.jpg", "/images/properties/property-3-arena.jpg", "/images/properties/property-3-mountain.jpg"],
    features: ["Hand-Hewn Beams", "Wood Stove", "Main-Level Primary Suite", "60x40 Workshop with Apartment", "Trail Access", "Mountain Views"],
    equestrianAmenities: {
      stalls: 2,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 2,
      pastureAcreage: 6,
      hasTackRoom: true,
      hasFeedRoom: false,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board"],
      waterSource: ["Well"],
      barnSquareFeet: 1200,
      additionalStructures: ["Workshop with Apartment"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-08-10",
    propertyType: "farm",
  },
  {
    id: "4",
    mlsNumber: "THC-001",
    title: "Lukas Farm - Premier Equestrian Facility",
    address: "Lambs Grill Road",
    city: "Rutherfordton",
    state: "NC",
    zipCode: "28139",
    price: 2600000,
    acreage: 37.59,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2900,
    yearBuilt: 1994,
    description: "Premier equestrian property featuring 28 custom-designed stalls with stunning mountain views. This 37+ acre facility includes a massive 100x220 irrigated covered arena, a 120x240 outdoor arena, and a separate 6-stall stallion barn. The 3-bedroom, 3-bath home with post-and-beam architecture features a tobacco barn workshop. Creek access, hiking trails, and panoramic mountain views complete this exceptional offering. Ideally located in the heart of North Carolina horse country near the Tryon International Equestrian Center.",
    images: ["/images/properties/property-4-hero.jpg", "/images/properties/property-4-barn.jpg", "/images/properties/property-4-view.jpg"],
    features: ["Post-and-Beam Architecture", "Mountain Views", "Creek Access", "Tobacco Barn Workshop", "Irrigated Arena", "No Restrictions"],
    equestrianAmenities: {
      stalls: 28,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 6,
      pastureAcreage: 20,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Electric"],
      waterSource: ["Well", "Creek"],
      barnSquareFeet: 12000,
      additionalStructures: ["Stallion Barn", "Workshop", "Equipment Storage"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-07-01",
    propertyType: "estate",
  },
  {
    id: "5",
    mlsNumber: "THC-002",
    title: "The Hayloft Equestrian Estate",
    address: "South River Road",
    city: "Tryon",
    state: "NC",
    zipCode: "28782",
    price: 2798999,
    acreage: 24.05,
    bedrooms: 5,
    bathrooms: 9,
    squareFeet: 3333,
    yearBuilt: 2008,
    description: "Three separate homes and an Olympic-quality riding arena define this extraordinary 24-acre equestrian estate in historic Hunting Country. The property features a 4-stall center-aisle barn and a 2-stall shed row barn, both impeccably maintained. Eight fenced paddocks provide flexible turnout options. The crown jewel is a 192x66 covered arena with professional lighting and quality footing. Direct access to the FETA trail system connects you to miles of riding throughout Tryon horse country. Located just minutes from the Tryon International Equestrian Center, this property offers the complete equestrian lifestyle.",
    images: ["/images/properties/property-5-hero.jpg", "/images/properties/property-5-arena.jpg", "/images/properties/property-5-pasture.jpg"],
    features: ["3 Separate Homes", "FETA Trail Access", "Olympic Arena", "Professional Lighting", "Historic Hunting Country", "Near TIEC"],
    equestrianAmenities: {
      stalls: 6,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 8,
      pastureAcreage: 16,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: false,
      fencingType: ["Board", "Vinyl"],
      waterSource: ["Well"],
      barnSquareFeet: 4800,
      additionalStructures: ["Second Barn", "Guest Home", "Caretaker Home"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-05-15",
    propertyType: "estate",
  },
  {
    id: "6",
    mlsNumber: "THC-003",
    title: "Hidden Hollow Farm",
    address: "Peniel Road",
    city: "Columbus",
    state: "NC",
    zipCode: "28722",
    price: 4995000,
    acreage: 92,
    bedrooms: 4,
    bathrooms: 6,
    squareFeet: 4917,
    yearBuilt: 2015,
    description: "Hidden Hollow Farm is a 92-acre mountain paradise featuring a private waterfall, 180-degree Blue Ridge Mountain views, and world-class equestrian facilities. The Wellington-style barn houses 6 premium stalls with rubber matting, fans, and auto waterers, plus a 2-bedroom apartment and fully equipped riders lounge. The luxury 4-bedroom, 6-bath residence showcases the finest finishes with an open floor plan designed to frame the stunning panoramic views. A private pool, FETA trail access, and proximity to the Tryon International Equestrian Center make this one of the most coveted equestrian estates in the Southeast.",
    images: ["/images/properties/property-6-hero.jpg", "/images/properties/property-6-barn.jpg", "/images/properties/property-6-mountain.jpg"],
    features: ["Private Waterfall", "180-Degree Mountain Views", "Pool", "Wellington-Style Barn", "Riders Lounge", "FETA Trail Access"],
    equestrianAmenities: {
      stalls: 6,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 4,
      pastureAcreage: 30,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: false,
      fencingType: ["Board", "Vinyl"],
      waterSource: ["Well", "Spring"],
      barnSquareFeet: 5000,
      additionalStructures: ["2BR Apartment", "Riders Lounge", "Equipment Barn"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-04-20",
    propertyType: "estate",
  },
  {
    id: "7",
    mlsNumber: "THC-004",
    title: "Turnkey Horse Property on Lambs Grill Road",
    address: "Lambs Grill Road",
    city: "Rutherfordton",
    state: "NC",
    zipCode: "28139",
    price: 1100000,
    acreage: 20,
    bedrooms: 4,
    bathrooms: 5,
    squareFeet: 2437,
    yearBuilt: 1929,
    description: "A beautifully restored 1929 home on 20 acres in the heart of NC horse country, this turnkey horse property is ready for riders of all levels. The 4-stall center-aisle barn with loft provides the main facility, complemented by an 8+ stall shed row barn with tack room and wash racks. A large riding arena and round pen offer ample training space. The lovingly renovated home preserves original character while incorporating modern updates throughout. Located minutes from the Tryon International Equestrian Center with easy access to trails and local equestrian services.",
    images: ["/images/properties/property-7-hero.jpg", "/images/properties/property-7-barn.jpg", "/images/properties/property-7-pasture.jpg"],
    features: ["Beautifully Restored 1929 Home", "Modern Updates", "Two Barns", "Round Pen", "Near TIEC", "Quiet Country Setting"],
    equestrianAmenities: {
      stalls: 12,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 4,
      pastureAcreage: 14,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Electric"],
      waterSource: ["Well"],
      barnSquareFeet: 5500,
      additionalStructures: ["Shed Row Barn", "Barn Loft"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-10-01",
    propertyType: "farm",
  },
  {
    id: "8",
    mlsNumber: "THC-005",
    title: "Rare Equestrian Opportunity Near TIEC",
    address: "Morningstar Lake Road",
    city: "Forest City",
    state: "NC",
    zipCode: "28043",
    price: 875000,
    acreage: 23.75,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 4178,
    yearBuilt: 2002,
    description: "Rare equestrian opportunity just 15 minutes from the Tryon International Equestrian Center. This 23+ acre property features a spacious 4-bedroom, 4-bathroom home with over 4,100 square feet of living space. The 44x60 metal barn includes 8 stalls with rubber mats, a tack room, and a workshop for equipment maintenance. Fenced pastures with creek frontage provide excellent turnout with natural water. The gently rolling terrain and mature hardwoods create a private, park-like setting while remaining close to town and all equestrian amenities.",
    images: ["/images/properties/property-8-hero.jpg", "/images/properties/property-8-barn.jpg", "/images/properties/property-8-creek.jpg"],
    features: ["Creek Frontage", "Mature Hardwoods", "Metal Barn", "Workshop", "15 Min to TIEC", "Fenced Pastures"],
    equestrianAmenities: {
      stalls: 8,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 3,
      pastureAcreage: 15,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board", "Wire"],
      waterSource: ["Well", "Creek"],
      barnSquareFeet: 2640,
      additionalStructures: ["Workshop"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-11-05",
    propertyType: "farm",
  },
  {
    id: "9",
    mlsNumber: "THC-006",
    title: "Small Horse Farm with Mountain Views",
    address: "Lake Adger Road",
    city: "Mill Spring",
    state: "NC",
    zipCode: "28756",
    price: 599800,
    acreage: 7.76,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 1188,
    yearBuilt: 1990,
    description: "Affordable small horse farm with year-round mountain views and income-generating potential. The property features a 120x70 riding arena, 6 rubber-matted stalls, and a 12x36 covered shelter. A separate ADU provides rental income or guest quarters. Fenced pastures and run-in shelters keep horses comfortable. Located just 13 miles from the Tryon International Equestrian Center, this property is perfect for a small boarding operation or private horse owner looking for an affordable entry into NC horse country.",
    images: ["/images/properties/property-9-hero.jpg", "/images/properties/property-9-barn.jpg", "/images/properties/property-9-mountain.jpg"],
    features: ["Mountain Views", "ADU for Rental Income", "Rubber-Matted Stalls", "Covered Shelter", "13 Miles to TIEC", "Boarding Potential"],
    equestrianAmenities: {
      stalls: 6,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 2,
      pastureAcreage: 4,
      hasTackRoom: true,
      hasFeedRoom: false,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board", "Electric"],
      waterSource: ["Well"],
      barnSquareFeet: 1800,
      additionalStructures: ["ADU", "Covered Shelter"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-12-01",
    propertyType: "farm",
  },
  {
    id: "10",
    mlsNumber: "NC-REALTY-001",
    title: "Gated Equestrian Estate on Preservation Trail",
    address: "Preservation Trail",
    city: "Columbus",
    state: "NC",
    zipCode: "28722",
    price: 3775000,
    acreage: 27.03,
    bedrooms: 8,
    bathrooms: 11,
    squareFeet: 7360,
    yearBuilt: 2012,
    description: "Exceptional gated equestrian estate ideal for teaching, boarding, and income production. Located just 6 miles from the Tryon International Equestrian Center, the property features a 19,296 sq ft barn with a 60x144 indoor arena with viewing room, 12 stalls (10 with 12x24 run-outs), multiple tack rooms, and wash bays. Solar power reduces operating costs. The 7,360 sq ft main residence offers 8 bedrooms and 11 bathrooms across multiple levels, perfect for hosting riders and guests. Rolling pastures and wooded trails complete this world-class facility.",
    images: ["/images/properties/property-10-hero.jpg", "/images/properties/property-10-barn.jpg", "/images/properties/property-10-aerial.jpg"],
    features: ["Gated Community", "Solar Powered", "Indoor Arena with Viewing Room", "12 Stalls with Run-Outs", "Income Producing", "6 Miles to TIEC"],
    equestrianAmenities: {
      stalls: 12,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 5,
      pastureAcreage: 15,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: false,
      fencingType: ["Board", "Vinyl"],
      waterSource: ["Well"],
      barnSquareFeet: 19296,
      additionalStructures: ["Solar Array", "Equipment Storage"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-06-01",
    propertyType: "estate",
  },
  {
    id: "11",
    mlsNumber: "NC-REALTY-002",
    title: "Affordable Horse Farm Near TIEC",
    address: "Big Island Road",
    city: "Forest City",
    state: "NC",
    zipCode: "28043",
    price: 449000,
    acreage: 6.25,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2202,
    yearBuilt: 1985,
    description: "Affordable horse farm only 11 minutes from the Tryon International Equestrian Center. This well-maintained property features a 2-stall barn with tack and feed room, a run-in shelter, and a round pen with footing. The 3-bedroom, 2-bath home offers over 2,200 sq ft with a massive family room and refinished hardwood floors throughout. Fenced pastures and mature trees create a private country setting. An ideal starter farm for riders wanting to be part of the thriving Tryon equestrian community without breaking the bank.",
    images: ["/images/properties/property-11-hero.jpg", "/images/properties/property-11-barn.jpg", "/images/properties/property-11-pasture.jpg"],
    features: ["Refinished Hardwood Floors", "Large Family Room", "Round Pen with Footing", "Run-in Shelter", "11 Min to TIEC", "Private Setting"],
    equestrianAmenities: {
      stalls: 2,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 2,
      pastureAcreage: 4,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: false,
      hasRoundPen: true,
      fencingType: ["Board"],
      waterSource: ["Well"],
      barnSquareFeet: 800,
      additionalStructures: ["Run-in Shelter"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2025-11-15",
    propertyType: "farm",
  },
  {
    id: "12",
    mlsNumber: "NC-REALTY-003",
    title: "Elizabeth Lane Equestrian Property",
    address: "803 Elizabeth Lane",
    city: "Matthews",
    state: "NC",
    zipCode: "28105",
    price: 2500000,
    acreage: 5,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 3600,
    yearBuilt: 1960,
    description: "Rare 5-acre equestrian property in the heart of Matthews with no HOA restrictions. This property previously accommodated horses with an existing barn featuring electricity, suitable for workshop or equestrian use. The 3,600 sq ft home includes wood floors, an updated kitchen, two primary suites perfect for multi-generational living, and an in-ground pool. The spacious lot offers room for a riding arena and multiple paddocks. An exceptional opportunity to create your own equestrian retreat close to Charlotte while enjoying the charm of historic Matthews.",
    images: ["/images/properties/property-12-hero.jpg", "/images/properties/property-12-pool.jpg", "/images/properties/property-12-land.jpg"],
    features: ["No HOA", "In-Ground Pool", "Wood Floors", "Updated Kitchen", "Two Primary Suites", "Multi-Generational Living"],
    equestrianAmenities: {
      stalls: 2,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 1,
      pastureAcreage: 3,
      hasTackRoom: false,
      hasFeedRoom: false,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board"],
      waterSource: ["Municipal"],
      barnSquareFeet: 1200,
      additionalStructures: ["Pool House"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2026-01-10",
    propertyType: "farm",
  },
];

export const blogPosts: BlogPost[] = [];
export const testimonials: Testimonial[] = [];
export const cities = ["Charlotte", "Columbus", "Forest City", "Matthews", "Mill Spring", "Mooresville", "Rutherfordton", "Tryon", "Waxhaw"];
export const stats = [
  { label: "Properties Listed", value: "50+" },
  { label: "Acres Represented", value: "1,200+" },
  { label: "Happy Clients", value: "200+" },
  { label: "Years Experience", value: "15+" },
];
