import { Property, Agent, TeamMember, BlogPost, Testimonial } from "@/types";

export const mockAgent: Agent = {
  id: "1",
  name: "Lara Murphy",
  title: "Broker / Owner",
  phone: "(704) 929-3289",
  email: "lara@carolinahorsefarmrealty.com",
  photo: "/images/team/lara-murphy.jpg",
  bio: "With over 15 years of experience in equestrian real estate.",
  specialties: ["Horse Farms", "Equestrian Estates", "Land for Horses"],
  licenseNumber: "NC-123456",
};

export const teamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Lara Murphy",
    title: "Broker / Owner",
    phone: "(704) 929-3289",
    email: "lara@carolinahorsefarmrealty.com",
    photo: "/images/team/lara-murphy.jpg",
    bio: "With over 15 years of experience in equestrian real estate.",
    specialties: ["Horse Farms", "Equestrian Estates", "Land for Horses"],
  },
];


export const mockProperties: Property[] = [
  {
    id: "1",
    mlsNumber: "MLS-001",
    title: "Stunning Equestrian Estate",
    address: "1234 Paddock Lane",
    city: "Waxhaw",
    state: "NC",
    zipCode: "28173",
    price: 2850000,
    acreage: 25,
    bedrooms: 5,
    bathrooms: 4.5,
    squareFeet: 6200,
    yearBuilt: 2018,
    description: "Magnificent equestrian estate with world-class facilities.",
    images: ["/images/properties/property-1.jpg"],
    features: ["Gated Entry", "Guest House", "Pool"],
    equestrianAmenities: {
      stalls: 12,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 6,
      pastureAcreage: 18,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Electric"],
      waterSource: ["Well", "Municipal"],
      barnSquareFeet: 8000,
      additionalStructures: ["Equipment Barn", "Hay Storage"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-10-15",
    propertyType: "estate",
  },
  {
    id: "2",
    mlsNumber: "MLS-002",
    title: "Charming Horse Farm",
    address: "567 Bridle Path Road",
    city: "Mooresville",
    state: "NC",
    zipCode: "28117",
    price: 1495000,
    acreage: 15,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 3800,
    yearBuilt: 2005,
    description: "Beautiful horse farm with updated amenities.",
    images: ["/images/properties/property-2.jpg"],
    features: ["Pond", "Workshop", "Three-car Garage"],
    equestrianAmenities: {
      stalls: 8,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 4,
      pastureAcreage: 10,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: false,
      fencingType: ["Board"],
      waterSource: ["Well"],
      barnSquareFeet: 4500,
      additionalStructures: ["Run-in Shed"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-11-01",
    propertyType: "farm",
  },
  {
    id: "3",
    mlsNumber: "MLS-003",
    title: "Premier Training Facility",
    address: "890 Champions Way",
    city: "Charlotte",
    state: "NC",
    zipCode: "28277",
    price: 4200000,
    acreage: 45,
    bedrooms: 6,
    bathrooms: 5.5,
    squareFeet: 8500,
    yearBuilt: 2020,
    description: "State-of-the-art training facility with luxury home.",
    images: ["/images/properties/property-3.jpg"],
    features: ["Wine Cellar", "Home Theater", "Smart Home"],
    equestrianAmenities: {
      stalls: 24,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 8,
      pastureAcreage: 30,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Vinyl", "Electric"],
      waterSource: ["Well", "Municipal"],
      barnSquareFeet: 15000,
      additionalStructures: ["Staff Quarters", "Hay Barn", "Equipment Storage"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-09-20",
    propertyType: "estate",
  },
  {
    id: "4",
    mlsNumber: "MLS-004",
    title: "Scenic Horse Property",
    address: "234 Valley View Drive",
    city: "Weddington",
    state: "NC",
    zipCode: "28104",
    price: 985000,
    acreage: 10,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 2800,
    yearBuilt: 2010,
    description: "Picturesque property with mountain views.",
    images: ["/images/properties/property-4.jpg"],
    features: ["Wrap-around Porch", "Fireplace", "Updated Kitchen"],
    equestrianAmenities: {
      stalls: 4,
      hasIndoorArena: false,
      hasOutdoorArena: true,
      pastures: 3,
      pastureAcreage: 7,
      hasTackRoom: true,
      hasFeedRoom: false,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board"],
      waterSource: ["Well"],
      barnSquareFeet: 2400,
      additionalStructures: [],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-11-10",
    propertyType: "farm",
  },
  {
    id: "5",
    mlsNumber: "MLS-005",
    title: "Prime Equestrian Land",
    address: "789 Rolling Hills Lane",
    city: "Tryon",
    state: "NC",
    zipCode: "28782",
    price: 650000,
    acreage: 30,
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 0,
    yearBuilt: 0,
    description: "Exceptional land ready for your dream equestrian facility.",
    images: ["/images/properties/property-5.jpg"],
    features: ["Creek Access", "Cleared Pastures", "Road Frontage"],
    equestrianAmenities: {
      stalls: 0,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 4,
      pastureAcreage: 25,
      hasTackRoom: false,
      hasFeedRoom: false,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board"],
      waterSource: ["Creek", "Well"],
      additionalStructures: [],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-10-25",
    propertyType: "land",
  },
  {
    id: "6",
    mlsNumber: "MLS-006",
    title: "Luxury Dressage Estate",
    address: "456 Saddle Ridge Court",
    city: "Pineville",
    state: "NC",
    zipCode: "28134",
    price: 3750000,
    acreage: 35,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 5800,
    yearBuilt: 2015,
    description: "European-inspired estate designed for dressage.",
    images: ["/images/properties/property-6.jpg"],
    features: ["European Design", "Chef's Kitchen", "Infinity Pool"],
    equestrianAmenities: {
      stalls: 16,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 5,
      pastureAcreage: 22,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Vinyl"],
      waterSource: ["Well", "Municipal"],
      barnSquareFeet: 10000,
      additionalStructures: ["Groom's Quarters", "Covered Riding Track"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-08-15",
    propertyType: "estate",
  },
  {
    id: "7",
    mlsNumber: "MLS-007",
    title: "Cozy Country Farm",
    address: "123 Meadow Lane",
    city: "Matthews",
    state: "NC",
    zipCode: "28105",
    price: 875000,
    acreage: 8,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2200,
    yearBuilt: 1998,
    description: "Perfect starter horse property with charm.",
    images: ["/images/properties/property-7.jpg"],
    features: ["Renovated Kitchen", "Hardwood Floors", "Screened Porch"],
    equestrianAmenities: {
      stalls: 3,
      hasIndoorArena: false,
      hasOutdoorArena: false,
      pastures: 2,
      pastureAcreage: 5,
      hasTackRoom: true,
      hasFeedRoom: false,
      hasWashRack: false,
      hasRoundPen: false,
      fencingType: ["Board", "Electric"],
      waterSource: ["Well"],
      barnSquareFeet: 1800,
      additionalStructures: ["Storage Shed"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-11-05",
    propertyType: "farm",
  },
  {
    id: "8",
    mlsNumber: "MLS-008",
    title: "Grand Hunter Jumper Estate",
    address: "999 Foxhunt Drive",
    city: "Waxhaw",
    state: "NC",
    zipCode: "28173",
    price: 5500000,
    acreage: 60,
    bedrooms: 7,
    bathrooms: 6.5,
    squareFeet: 10500,
    yearBuilt: 2022,
    description: "Ultimate competition facility for hunter/jumper enthusiasts.",
    images: ["/images/properties/property-8.jpg"],
    features: ["Grand Foyer", "Guest Wing", "Tennis Court", "Helipad"],
    equestrianAmenities: {
      stalls: 30,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 10,
      pastureAcreage: 40,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Vinyl", "Electric"],
      waterSource: ["Well", "Municipal", "Pond"],
      barnSquareFeet: 25000,
      additionalStructures: ["Manager's House", "Breeding Barn", "Veterinary Suite"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-07-01",
    propertyType: "estate",
  },
  {
    id: "9",
    mlsNumber: "MLS-009",
    title: "Turnkey Training Barn",
    address: "555 Canter Circle",
    city: "Cornelius",
    state: "NC",
    zipCode: "28031",
    price: 1895000,
    acreage: 18,
    bedrooms: 4,
    bathrooms: 3.5,
    squareFeet: 4200,
    yearBuilt: 2012,
    description: "Move-in ready training operation with established clientele.",
    images: ["/images/properties/property-9.jpg"],
    features: ["Office Suite", "Client Lounge", "Security System"],
    equestrianAmenities: {
      stalls: 14,
      hasIndoorArena: true,
      hasOutdoorArena: true,
      pastures: 4,
      pastureAcreage: 12,
      hasTackRoom: true,
      hasFeedRoom: true,
      hasWashRack: true,
      hasRoundPen: true,
      fencingType: ["Board", "Vinyl"],
      waterSource: ["Well", "Municipal"],
      barnSquareFeet: 9000,
      additionalStructures: ["Apartment above Barn"],
    },
    listingAgent: mockAgent,
    status: "active",
    listDate: "2024-10-01",
    propertyType: "farm",
  },
];

export const blogPosts: BlogPost[] = [];
export const testimonials: Testimonial[] = [];
export const cities = ["Charlotte", "Cornelius", "Matthews", "Mooresville", "Pineville", "Tryon", "Waxhaw", "Weddington"];
export const stats = [{ label: "Test", value: "1" }];